fanmento/admin/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('',
    (r'/login$', 'fanmento.admin.views.admin_login'),
    (r'/logout$', 'fanmento.admin.views.admin_logout'),
    (r'/users/reset/request$', 'fanmento.admin.views.request_password_reset'),
    (r'/users/image/delete$', 'fanmento.admin.views.delete_image'),
    (r'/users/reset$', 'fanmento.admin.views.reset_password'),
    (r'/users/delete$', 'fanmento.admin.views.delete_user'),
    (r'/users/new$', 'fanmento.admin.views.create_user'),
    (r'/users/(?P<user_id>[^/]+)$', 'fanmento.admin.views.user_detail'),
    (r'/users$', 'fanmento.admin.views.users'),
    (r'/venues/delete$', 'fanmento.admin.views.delete_venue'),
    (r'/venues/new$', 'fanmento.admin.views.create_venue'),
    (r'/venues/(?P<venue_id>[^/]+)$', 'fanmento.admin.views.venue_detail'),
    (r'/venues$', 'fanmento.admin.views.venues'),
    (r'/advertisements/delete$', 'fanmento.admin.views.delete_advertisement'),
    (r'/advertisements/new$', 'fanmento.admin.views.create_advertisement'),
    (r'/advertisements/(?P<ad_id>[^/]+)$', 'fanmento.admin.views.advertisement_detail'),
    (r'/advertisements$', 'fanmento.admin.views.advertisements'),
    (r'/templates/delete$', 'fanmento.admin.views.delete_template'),
    (r'/templates/new$', 'fanmento.admin.views.create_template'),
    (r'/templates/(?P<template_id>[^/]+)$', 'fanmento.admin.views.template_detail'),
    (r'/templates$', 'fanmento.admin.views.templates'),
    (r'/backgrounds/delete$', 'fanmento.admin.views.delete_background'),
    (r'/backgrounds/new$', 'fanmento.admin.views.create_background'),
    (r'/backgrounds/(?P<bg_id>[^/]+)$', 'fanmento.admin.views.background_detail'),
    (r'/backgrounds$', 'fanmento.admin.views.backgrounds'),
    (r'/$', 'fanmento.admin.views.index'),
)

fanmento/fantemplate/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from mvp.models import Resource
from piston.authentication import HttpBasicAuthentication
from api import *

authentication = {
    'authentication': HttpBasicAuthentication(realm='fanmento')
}

urlpatterns = patterns('',
    (r'venue$', Resource(handler=VenueHandler, **authentication)),
    (r'ad/(?P<ad_id>[^/]+)/image$', 'fanmento.fantemplate.views.ad_image'),
    (r'ad/(?P<template_id>[^/]+)/?$', Resource(handler=AdvertisementHandler, **authentication)),
    (r'category$', Resource(handler=CategoryHandler, **authentication)),
    (r'background/(?P<bg_id>[^/]+)/image', 'fanmento.fantemplate.views.background_image'),
    (r'template/(?P<template_id>[^/]+)/image', 'fanmento.fantemplate.views.template_image'),
    (r'template/(?P<code>[^/]+)', Resource(handler=TemplateByCodeHandler, **authentication)),
    (r'template', Resource(handler=TemplateByQueryHandler, **authentication)),
)

fanmento/urls.py
from django.conf.urls.defaults import patterns, include

urlpatterns = patterns(
    '',
    (r'^api/v1/user/', include('fanmento.users.urls')),
    (r'^api/v1/templates/', include('fanmento.fantemplate.urls')),
    (r'^admin', include('fanmento.admin.urls')),
    (
        r'^mu-7e31d595-0ab0489f-8b41e6f9-953ab3e6',
        'fanmento.fantemplate.views.blitz_io'
    ),
)

fanmento/users/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

from mvp.models import Resource
from piston.authentication import HttpBasicAuthentication
from api import *

authentication = {
    'authentication': HttpBasicAuthentication(realm='fanmento')
}

urlpatterns = patterns('',
    (r'reset/clear$', Resource(handler=ResetTokenHandler)),
    (r'image/(?P<image_id>[^/]+)/?$', Resource(handler=UserImageDetailHandler, **authentication)),
    (r'image/?$', Resource(handler=UserImageHandler, **authentication)),
    (r'(?P<user_id>[^/]+)$', Resource(handler=UserHandler, **authentication)),
    (r'$', Resource(handler=UserHandler, **authentication)),
)

fanmento/admin/models.py
from django.db import models

# Create your models here.

fanmento/fantemplate/models.py
from google.appengine.ext.db import to_dict
from google.appengine.ext import db

from geo.geomodel import GeoModel

from gae_utilities.models import BlobModel


class Venue(GeoModel):
    name = db.StringProperty()
    address = db.PostalAddressProperty()
    start_date = db.DateProperty()
    end_date = db.DateProperty()

    def date_string(self):
        start_date = self.start_date.strftime("%m/%d/%Y")
        end_date = self.end_date.strftime("%m/%d/%Y")

        return '%s - %s' % (start_date, end_date)

    def unlink_templates(self):
        templates = self.template_set
        for template in templates:
            template.venue = None
            template.put()

    def to_dict(self):
        result = to_dict(self)
        result['id'] = self.key().id()

        return result

    def delete(self):
        self.unlink_templates()
        super(Venue, self).delete()


class Advertisement(BlobModel):
    name = db.StringProperty()
    description = db.TextProperty()
    company = db.StringProperty()
    link = db.StringProperty()
    clicks = db.IntegerProperty()
    impressions = db.IntegerProperty()

    def unlink_templates(self):
        templates = self.template_set
        for template in templates:
            template.advertisement = None
            template.put()

    def delete(self):
        self.unlink_templates()
        super(Advertisement, self).delete()


class Background(BlobModel):
    name = db.StringProperty()
    description = db.TextProperty()

    def unlink_templates(self):
        templates = self.template_set
        for template in templates:
            template.background = None
            template.put()

    def delete(self):
        self.unlink_templates()
        super(Background, self).delete()


class Template(BlobModel):
    EFFECTS = (
        (0, 'Normal'),
        (1, 'Luma'),
        (2, 'Emboss'),
        (3, 'BlackWhite'),
        (4, 'Sepia'),
        (5, 'Toon'),
        (6, 'Threshold'),
        (7, 'Adaptive'),
        (8, 'Posterize'),
        (9, 'PolkaNil'),
        (10, 'PolkaMedium'),
        (11, 'PolkaLarge'),
        (12, 'Crosshatch'),
        (13, 'TrueBlue'),
        (14, 'NavyBlue'),
        (15, 'BullsRed'),
        (16, 'Gold'),
        (17, 'Yellow'),
        (18, 'HotOrange'),
        (19, 'TrueOrange'),
        (20, 'LimeGreen'),
        (21, 'DarkGreen'),
        (22, 'Purple'),
    )

    name = db.StringProperty()
    category = db.CategoryProperty()
    product_id = db.StringProperty()
    description = db.TextProperty()
    effect = db.CategoryProperty()
    advertisement = db.ReferenceProperty(reference_class=Advertisement)
    venue = db.ReferenceProperty(reference_class=Venue)
    code = db.StringProperty()
    background = db.ReferenceProperty(reference_class=Background)
    twitter_message = db.TextProperty()
    facebook_message = db.TextProperty()
    email_message = db.TextProperty()
    client_name = db.StringProperty()

    def to_dict(self):
        result = to_dict(self)

        result['id'] = self.key().id()
        result['effect'] = int(result['effect'])

        try: 
            result['advertisement'] = to_dict(self.advertisement)
        except: result['advertisement'] = {}

        try: result['venue'] = to_dict(self.venue)
        except: result['venue'] = {}

        try:
            result['background'] = to_dict(self.background)
        except: result['background'] = {}

        try: del result['venue']['location_geocells']
        except: pass

        return result

fanmento/fantemplate/forms.py
from django import forms
from django.contrib.localflavor.us.forms import USStateField, USZipCodeField
from django.utils.safestring import mark_safe
from django.forms import widgets

from google.appengine.ext import db

from bootstrap.forms import BootstrapForm, Fieldset

import logging

from models import *

class CalendarWidget(widgets.TextInput):
    def render(self, name, value, attrs=None):
        return mark_safe(u'''
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-calendar"></i></span>%s
                </div>
                ''' % (super(CalendarWidget, self).render(name, value, attrs)))

class VenueForm(BootstrapForm):
    class Meta:
        layout = (
            Fieldset("Update a venue", 
                "name", 
                "street", 
                "city", 
                "state",
                "zip",
                "latitude",
                "longitude",
                "valid_dates",
            ),
        )

    name        = forms.CharField(max_length=75)
    street      = forms.CharField(max_length=75)
    city        = forms.CharField(max_length=25)
    state       = USStateField()
    zip         = USZipCodeField()
    latitude    = forms.DecimalField()
    longitude   = forms.DecimalField()
    valid_dates = forms.CharField(widget=CalendarWidget)

class AdvertisementForm(BootstrapForm):
    error_css_class = 'error'
    required_css_class = 'required'

    name        = forms.CharField(max_length=75)
    image       = forms.FileField(required=False)
    description = forms.CharField(widget=forms.Textarea)
    company     = forms.CharField(max_length=75)
    link        = forms.CharField(max_length=75)

class PriceWidget(widgets.TextInput):
    def render(self, name, value, attrs=None):
        return mark_safe(u'''<div class="input-prepend input-append"><span class="add-on">$</span>%s</div>''' % (super(PriceWidget, self).render(name, value, attrs)))

class TemplateForm(BootstrapForm):
    error_css_class = 'error'
    required_css_class = 'required'

    def __init__(self, *args, **kwargs):
        super(TemplateForm, self).__init__(*args, **kwargs)
        
        q = db.Query(Advertisement, projection=("name",))
        ads = q.run(batch_size=1000)

        self.fields['advertisement'] = forms.ChoiceField(choices=[(a.key().id(), a.name) for a in ads])

        q = db.Query(Venue, projection=("name",))
        venues = q.run(batch_size=1000)

        venue_choices = [(v.key().id(), v.name) for v in venues]
        venue_choices.insert(0, ('None', None))
        self.fields['venue'] = forms.ChoiceField(choices=venue_choices)

        q = db.Query(Background, projection=("name",))
        backgrounds = q.run(batch_size=1000)

        self.fields['background'] = forms.ChoiceField(choices=[(b.key().id(), b.name) for b in backgrounds])

    CATEGORIES = (
        ('sports', 'Sports'),
        ('entertainment', 'Entertainment'),
        ('music', 'Music'),
        ('lifestyle', 'Lifestyle'),
        ('miscellaneous', 'Miscellaneous'),
    )

    name             = forms.CharField(max_length=75)
    image            = forms.FileField(required=True)
    code             = forms.CharField(max_length=5)
    product_id       = forms.CharField(max_length=50, label="IAP Product ID", required=False)
    category         = forms.ChoiceField(choices=CATEGORIES)
    description      = forms.CharField(widget=forms.Textarea)
    effect           = forms.ChoiceField(choices=Template.EFFECTS)
    twitter_message  = forms.CharField(widget=forms.Textarea, required=False)
    facebook_message = forms.CharField(widget=forms.Textarea, required=False)
    email_message    = forms.CharField(widget=forms.Textarea, required=False)
    client_name      = forms.CharField(max_length=75, required=False)

class UpdateTemplateForm(TemplateForm):
    image            = forms.FileField(required=False)

class TemplateQueryForm(forms.Form):
    latitude  = forms.DecimalField(required=False)
    longitude = forms.DecimalField(required=False)
    category  = forms.CharField(required=False)

class BackgroundForm(BootstrapForm):
    error_css_class = 'error'
    required_css_class = 'required'

    name        = forms.CharField(max_length=75)
    image       = forms.FileField(required=False)
    description = forms.CharField(widget=forms.Textarea)

fanmento/users/forms.py
from django import forms
from django.contrib.localflavor.us.forms import USPhoneNumberField

from bootstrap.forms import BootstrapForm, Fieldset

class CreateUserForm(BootstrapForm):
    email          = forms.CharField(max_length=75)
    password       = forms.CharField(widget=forms.PasswordInput(), max_length=100, required=False)
    facebook_token = forms.CharField(required=False)
    name           = forms.CharField(required=False)

class RegistrationResourceForm(BootstrapForm):
    class Meta:
        layout = (
            Fieldset("Update a user", "name", "email", "password", "admin"),
        )

    name     = forms.CharField(max_length=75, required=False)
    email    = forms.CharField(max_length=75)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=100, required=False)
    admin    = forms.BooleanField(required=False)

class ResetPasswordForm(BootstrapForm):
    password = forms.CharField(max_length=100, label="Password")
    confirm = forms.CharField(max_length=100, label="Confirm")
    token = forms.CharField(max_length=100)

class RequestResetPasswordForm(BootstrapForm):
    email = forms.CharField(max_length=100, label="Email")

class UserImageForm(forms.Form):
    #image          = forms.FileField(required=True)
    background_url   = forms.CharField(required=False)
    twitter_message  = forms.CharField(widget=forms.Textarea, required=False)
    facebook_message = forms.CharField(widget=forms.Textarea, required=False)
    email_message    = forms.CharField(widget=forms.Textarea, required=False)
    client_name      = forms.CharField(max_length=75, required=False) 

class ImageDeleteForm(forms.Form):
    user_id  = forms.IntegerField(required=True)
    image_id = forms.IntegerField(required=True)

fanmento/fantemplate/views.py
from django.http import HttpResponse

from models import *


def image_response(model):
    if model:
        return model.get_blob_response()

    response = HttpResponse()
    response.status_code = 404

    return response


def background_image(request, bg_id):
    return image_response(Background.get_by_id(int(bg_id)))


def template_image(request, template_id):
    return image_response(Template.get_by_id(int(template_id)))


def ad_image(request, ad_id):
    return image_response(Advertisement.get_by_id(int(ad_id)))


def blitz_io(request):

    """ Used to validate ownership of the site for Blitz.io testing"""

    return HttpResponse('42')

fanmento/templates/ads_list.html
{% extends "resource_list.html" %}

{% block thead %}
<th><a href="?sort={% if sort == 'name' %}-{% endif %}name">Name</a></th>
<th><a href="?sort={% if sort == 'company' %}-{% endif %}company">Company</a></th>
<th><a href="?sort={% if sort == 'clicks' %}-{% endif %}clicks">Clicks</a></th>
<th><a href="?sort={% if sort == 'impressions' %}-{% endif %}impressions">Impressions</a></th>
{% endblock %}

{% block rows %}
{% for ad in page.object_list %}
    <tr>
        <td><input id="{{ ad.key.id }}" class="resource-row" type="checkbox"></td>
        <td><a href="{% url fanmento.admin.views.advertisement_detail ad.key.id %}">{{ ad.name }}</a></td>
        <td>{{ ad.company }}</td>
        <td>{{ ad.clicks }}</td>
        <td>{{ ad.impressions }}</td>
    </tr>
{% endfor %}
{% endblock %}

{% block create_uri %}{% url fanmento.admin.views.create_advertisement %}{% endblock %}
{% block delete_uri %}{% url fanmento.admin.views.delete_advertisement %}{% endblock %}

fanmento/templates/background_list.html
{% extends "resource_list.html" %}

{% block thead %}
<th>Name</th>
{% endblock %}

{% block rows %}
{% for background in page.object_list %}
    <tr>
        <td><input id="{{ background.key.id }}" class="resource-row" type="checkbox"></td>
        <td><a href="{% url fanmento.admin.views.background_detail background.key.id %}">{{ background.name }}</a></td>
    </tr>
{% endfor %}
{% endblock %}

{% block create_uri %}{% url fanmento.admin.views.create_background %}{% endblock %}
{% block delete_uri %}{% url fanmento.admin.views.delete_background %}{% endblock %}

fanmento/templates/background_new.html
{% extends "index.html" %}

{% block content %}

<form enctype="multipart/form-data" method="POST" action="{% if update %}{% url fanmento.admin.views.background_detail background_id %}{% else %}{% url fanmento.admin.views.create_background %}{% endif %}" class="form-horizontal" accept-charset="UTF-8">
    {% csrf_token %}
    <legend>{% if update %}Update{% else %}Create{% endif %} a background</legend>
    {{ form.non_field_errors }}

    {% for field in form %}
    <div id="div_{{ field.auto_id }}" class="control-group {{ field.css_classes }}">
        <label class="control-label" for="id_name">{{ field.label }}</label>
        <div class="controls">
            {% if field.label == "Image" and update %}
            <div class="existing-image">
                <img src="/api/v1/templates/background/{{ background_id }}/image" width="100px" />
            </div>
            {% endif %}
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                <span class="help-inline">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <div class="form-actions">
        <button type="submit" name="submit" class="btn btn-success">{% if update %}Update{% else %}Create{% endif %}</button>
    </div>
</form>

{% endblock %}

fanmento/templates/index.html
{% extends "site_base.html" %}

{% block body %}
<div class="navbar navbar-inverse">
	<div class="navbar-inner">
		<div class="container-fluid">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a class="brand" href="#" name="top">Fanmento Admin</a>
			<div class="nav-collapse collapse">
				<div class="btn-group pull-right">
					<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user"></i> {{ name }} <span class="caret"></span>
					</a>
					<ul class="dropdown-menu">
						<li><a href="{% url fanmento.admin.views.admin_logout %}"><i class="icon-share"></i> Logout</a></li>
					</ul>
				</div>
			</div>
			<!--/.nav-collapse -->
		</div>
		<!--/.container-fluid -->
	</div>
	<!--/.navbar-inner -->
</div>
<div class="row-fluid">
    <div class="sidebar-nav span3">
        <div class="well" style="padding: 8px 0;">
            <ul class="nav nav-list"> 
              <li class="nav-header">Admin Menu</li>        
              <li {% if active == "users" %}class="active"{% endif %}><a href="{% url fanmento.admin.views.users %}"><i class="icon-user"></i> Users</a></li>
              <li {% if active == "venues" %}class="active"{% endif %}><a href="{% url fanmento.admin.views.venues %}"><i class="icon-map-marker"></i> Venues</a></li>
              <li {% if active == "advertisements" %}class="active"{% endif %}><a href="{% url fanmento.admin.views.advertisements %}"><i class="icon-bullhorn"></i> Advertisements</a></li>
              <li {% if active == "backgrounds" %}class="active"{% endif %}><a href="{% url fanmento.admin.views.backgrounds %}"><i class="icon-picture"></i> Backgrounds</a></li>
              <li {% if active == "templates" %}class="active"{% endif %}><a href="{% url fanmento.admin.views.templates %}"><i class="icon-list-alt"></i> Templates</a></li>
              <li class="divider"></li>
              <li><a href="{% url fanmento.admin.views.admin_logout %}"><i class="icon-share"></i> Logout</a></li>
            </ul>
        </div>
    </div>
    <div class="span8">
    {% block content %}
    {% endblock %}
    </div>
</div>
<!--/.navbar -->
{% endblock %}

fanmento/templates/login.html
{% extends "site_base.html" %}

{% block body %}
<div class="container">
	<div class="row">
		<div class="span4 offset4 well">
			<legend>Please Sign In</legend>
            {% if error %}
          	<div class="alert alert-error">
                <a class="close" data-dismiss="alert" href="#">×</a>Incorrect Username or Password!
            </div>
            {% endif %}
            {% if alert %}
          	<div class="alert alert-success">
                <a class="close" data-dismiss="alert" href="#">×</a>{{ alert }}
            </div>
            {% endif %}
            <form method="POST" action="{% url fanmento.admin.views.admin_login %}" accept-charset="UTF-8">
                {% csrf_token %}
                <input type="text" id="username" class="span4" name="username" placeholder="Username">
                <input type="password" id="password" class="span4" name="password" placeholder="Password">
                <button type="submit" name="submit" class="btn btn-info btn-block">Sign in</button>
			</form>    
		</div>
	</div>
</div>
{% endblock %}

fanmento/templates/request_password_reset.html
{% extends "site_base.html" %}

{% block body %}

<div class="container">
	<div class="row">
		<div class="span4 offset4 well">
			<legend>Request a New Password</legend>
            {% if done %}
          	<div class="alert alert-error">
                <a class="close" data-dismiss="alert" href="#">×</a>{{ error }}
            </div>
            {% endif %}
            {% if email %}
          	<div class="alert">
                <a class="close" data-dismiss="alert" href="#">×</a>Thank you. We have sent an email to {{ email }} with instructions on how to reset your password.
            </div>
            {% endif %}
            <form method="POST" action="{% url fanmento.admin.views.request_password_reset %}" accept-charset="UTF-8">
                {% csrf_token %}
                <input type="text" id="email" class="span4" name="email" placeholder="Email">
                {{form.email.errors}}
                <button type="submit" name="submit" class="btn btn-info btn-block">Request Reset</button>
			</form>    
		</div>
	</div>
</div>

{% endblock %}

fanmento/templates/reset_password.html
{% extends "site_base.html" %}

{% block body %}

<div class="container">
	<div class="row">
		<div class="span4 offset4 well">
			<legend>Reset Password</legend>
            {% if error %}
          	<div class="alert alert-error">
                <a class="close" data-dismiss="alert" href="#">×</a>{{ error }}
            </div>
            {% endif %}
            <form method="POST" action="{% url fanmento.admin.views.reset_password %}" accept-charset="UTF-8">
                {% csrf_token %}
                <input type="hidden" id="token" name="token" value="{{ token }}" />
                <input type="password" id="password" class="span4" name="password" placeholder="Password">
                <input type="password" id="confirm" class="span4" name="confirm" placeholder="Confirm">
                <button type="submit" name="submit" class="btn btn-info btn-block">Reset</button>
			</form>    
		</div>
	</div>
</div>

{% endblock %}

fanmento/templates/site_base.html
<!doctype html>
<html>
    <head>
        <title>{{ title }}</title>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
        <link type="text/css" rel="stylesheet" href="/css/bootstrap.min.css" />
        <link type="text/css" rel="stylesheet" href="/css/bootstrap-responsive.min.css" />
        <link type="text/css" rel="stylesheet" href="/css/site_base.css" />
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
        <script src="/js/underscore.min.js"></script>
        {% block includes %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
        <script src="/js/less.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script src="/js/bootstrap-modal.js"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>

fanmento/templates/templates_list.html
{% extends "resource_list.html" %}

{% block thead %}
<th><a href="?sort={% if sort == 'name' %}-{% endif %}name">Name</a></th>
<th><a href="?sort={% if sort == 'code' %}-{% endif %}code">Code</a></th>
<th><a href="?sort={% if sort == 'category' %}-{% endif %}category">Category</a></th>
<th><a href="?sort={% if sort == 'venue' %}-{% endif %}venue">Venue</a></th>
{% endblock %}

{% block rows %}
{% for template in page.object_list %}
    <tr>
        <td><input id="{{ template.key.id }}" class="resource-row" type="checkbox"></td>
        <td><a href="{% url fanmento.admin.views.template_detail template.key.id %}">{{ template.name }}</a></td>
        <td>{{ template.code }}</td>
        <td>{{ template.category }}</td>
        <td>{{ template.venue.name }}</td>
    </tr>
{% endfor %}
{% endblock %}

{% block create_uri %}{% url fanmento.admin.views.create_template %}{% endblock %}
{% block delete_uri %}{% url fanmento.admin.views.delete_template %}{% endblock %}

fanmento/templates/templates_new.html
{% extends "index.html" %}

{% block content %}

<form enctype="multipart/form-data" method="POST" action="{% if update %}{% url fanmento.admin.views.template_detail template_id %}{% else %}{% url fanmento.admin.views.create_template %}{% endif %}" class="form-horizontal" accept-charset="UTF-8">
    {% csrf_token %}
    <legend>{% if update %}Update{% else %}Create{% endif %} a template</legend>
    {{ form.non_field_errors }}

    {% for field in form %}
    <div id="div_{{ field.auto_id }}" class="control-group {{ field.css_classes }}">
        <label class="control-label" for="id_name">{{ field.label }}</label>
        <div class="controls">
            {% if field.label == "Image" and update %}
            <div class="existing-image">
                <img src="/api/v1/templates/template/{{ template_id }}/image" width="100px" />
            </div>
            {% endif %}
            {{ field }}
            {% if field.errors %}
                {% for error in field.errors %}
                <span class="help-inline">{{ error }}</span>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <div class="form-actions">
        <button type="submit" name="submit" class="btn btn-success">{% if update %}Update{% else %}Create{% endif %}</button>
    </div>
</form>

{% endblock %}

fanmento/templates/users_list.html
{% extends "resource_list.html" %}

{% block thead %}
<th><a href="?sort={% if sort == 'email' %}-{% endif %}email">Email</a></th>
<th><a href="?sort={% if sort == 'name' %}-{% endif %}name">Name</a></th>
{% endblock %}

{% block rows %}
{% for user in page.object_list %}
    <tr>
        <td><input id="{{ user.key.id }}" class="resource-row" type="checkbox"></td>
        <td><a href="{% url fanmento.admin.views.user_detail user.key.id %}">{{ user.email }}</a></td>
        <td>{{ user.name }}</td>
    </tr>
{% endfor %}
{% endblock %}

{% block create_uri %}{% url fanmento.admin.views.create_user %}{% endblock %}
{% block delete_uri %}{% url fanmento.admin.views.delete_user %}{% endblock %}

fanmento/templates/venues_new.html
{% extends "index.html" %}

{% block includes %}
<link type="text/css" rel="stylesheet" href="/css/daterangepicker.css" />
<script src="/js/date.js"></script>
<script src="/js/daterangepicker.js"></script>
{% endblock %}

{% block content %}

<form method="POST" action="{% if update %}{% url fanmento.admin.views.venue_detail venue_id %}{% else %}{% url fanmento.admin.views.create_venue %}{% endif %}" class="form-horizontal" accept-charset="UTF-8">
    {% csrf_token %}
    {{ form }}
    <div class="form-actions">
        <button type="submit" name="submit" class="btn btn-success">Create</button>
    </div>
</form>

<script type="text/javascript">
    $(document).ready(function() {
        $('#id_valid_dates').daterangepicker();
    });
</script>

{% endblock %}